[package]
name = "rust_wasm_hello_world"
version = "0.1.0"
authors = ["Volodymyr Khytskyi <khytsky.vladimir@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.28"
